# SonarQube configuration for ZenTask
sonar.projectKey=task-management-system
sonar.projectName=ZenTask
sonar.projectVersion=1.0

# Paths to source code
sonar.sources=Backend/ZenTask.API/ZenTask.API, Frontend/src
sonar.tests=ZenTask.Tests

# Language specific settings
sonar.language=c#
sonar.javascript.file.suffixes=.js,.jsx

# Exclusions
sonar.exclusions=**/obj/**, **/bin/**, **/node_modules/**, **/build/**, **/Migrations/**
